version: "3.8"
services:
  springboot-container:
    build:
      context: ./backend/spring-boot-docnct
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - 8081:8080
    restart: on-failure

  angular-container:
    build:
      context: ./frontend/docnct
      dockerfile: Dockerfile
    ports:
      - 81:80
